export const USER_AUTH_LOGIN = "FETCH_USER";
export const USER_AUTH_SIGNUP = "ADD_USER";
export const USER_AUTH_LOGOUT = "USER_AUTH_LOGOUT";
export const USER_ARTICLE_LIST = "USER_ARTICLE_LIST";
export const USER_ARTICLE_ADD = "USER_ARTICLE_ADD";
export const USER_ARTICLE_UPDATE = "USER_ARTICLE_UPDATE";
export const PUBLIC_ARTICLE_LIST = "PUBLIC_ARTICLE_LIST";
